# User Configuration Variables
OUTPUT_DIR : sqlite_db
EMAIL : myusername@domain.com
API_KEY :
FORCE_PAUSE_SECONDS : 1
DATABASE : megapestis.sqlite

# NCBI Tables to Query
TABLES :
  - Assembly
  - BioSample
  - SRA

# Query Terms to Use
SEARCH_TERMS :
  - Assembly : SAMN0
  - BioSample: SAMN0
  - SRA : SAMN0

# Columns of the database (ie. metadata fields to retrieve)
TABLE_COLUMNS :

  - Assembly :
    - AssemblyAccession : AssemblyAccession
    - AssemblyBioSampleAccession : BioSampleAccn
    - AssemblySpeciesName : SpeciesName
    - AssemblyInfraspecies : InfraspeciesList, Sub_value
    - AssemblyFTPGenbank : FtpPath_GenBank
    - AssemblyFTPRefSeq : FtpPath_RefSeq
    - AssemblyComment : NullValue

  - BioSample :
    - BioSampleAccession: BioSample, accession
    - BioSampleAccessionSecondary: NullValue
    - BioSampleOrganism: Description, OrganismName
    - BioSampleStrain: Attribute, harmonized_name, strain
    - BioSampleBiovar: Attribute, harmonized_name, biovar
    - BioSampleBranch: NullValue
    - BioSampleCollectionDate: Attribute, harmonized_name, collection_date
    - BioSampleGeographicLocation: Attribute, harmonized_name, geo_loc_name
    - BioSampleHost: Attribute, harmonized_name, host
    - BioSampleComment : NullValue

  - SRA :
    - SRABioSampleAccession : RUN_SET, RUN, Pool, EXTERNAL_ID, namespace, BioSample
    - SRARunAccession : RUN, accession
    - SRAPlatform : PLATFORM
    - SRAInstrumentModel : PLATFORM, INSTRUMENT_MODEL
    - SRAComment : NullValue
