# Snakemake Configuration File

# Directories
results_dir: "results"

# SQLITE Parameters
sqlite_db : "yersinia_pestis_db.sqlite"

sqlite_select_command_asm : SELECT
                              AssemblyFTPGenbank
                            FROM
                              BioSample
                            LEFT JOIN Assembly
                              ON AssemblyBioSampleAccession = BioSampleAccession
                            WHERE
                              (BioSampleComment LIKE '%KEEP%') AND
                              (BioSampleBranch NOT LIKE '%0.PE%') AND
                              (CAST(BioSampleCollectionDate as date) >= 1776) AND
                              (CAST(BioSampleCollectionDate as date) < 2008) AND
                              (length(AssemblyFTPGenbank) > 0)

sqlite_select_command_sra : SELECT
                              BioSampleAccession,
                              SRARunAccession
                            FROM
                              BioSample
                            LEFT JOIN SRA
                              ON SRABioSampleAccession = BioSampleAccession

sqlite_select_command_local : SELECT
                              BioSampleAccession
                            FROM
                              BioSample

sqlite_select_command_ref : SELECT AssemblyFTPGenbank FROM BioSample
    LEFT JOIN Assembly
      ON AssemblyBioSampleAccession = BioSampleAccession
      WHERE
      (BioSampleComment LIKE '%Assembly%Modern%Reference%')

# Dataset size
max_datasets_assembly : 3
max_datasets_sra : 0
reads_origin :
  - "assembly"

# misc filtering
detect_repeats_threshold : 90
detect_repeats_length : 50

reference_locus : "AL590842"
reference_locus_name : "chromosome"
reference_locus_start : "0"
reference_locus_end : "4653728"

# Eager param
eager_rev: "2.2.1"
eager_clip_readlength : 35
eager_bwaalnn : 0.01
eager_bwaalnl : 16
eager_other : '--mergedonly'
organism : "Yersinia pestis"
# Adapter Removal Defaults
eager_forward_adapter : 'AGATCGGAAGAGCACACGTCTGAACTCCAGTCACNNNNNNATCTCGTATGCCGTCTTCTGCTTG'
eager_reverse_adapter : 'AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTAGATCTCGGTGGTCGCCGTATCATT'

# Snippy Parameters
snippy_ctg_depth : 10
snippy_bam_depth : 3
snippy_base_qual : 20
snippy_map_qual : 30
snippy_min_frac : 0.9
snippy_mask_char : "X"
snippy_missing_data : 1
snippy_snp_density : 10
# Make this an empty string if removing singletons
snippy_keep_singleton: ""
#snippy_keep_singleton : "--keep-singleton"
snippy_multi_plot_missing_data:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  - 10

# IQTREE
iqtree_model: "-m MFP"
iqtree_seed : "13587543" # keeping it consistent in a config file allows for checkpointing
iqtree_outgroup : "GCA_009667885.1_ASM966788v1_genomic,GCA_000323665.1_ASM32366v1_genomic" # This is the MRCA of 0.ANT1
iqtree_other : "--ufboot 1000"
iqtree_runs : 1 # 1 for testing, 10 for production
